# Dependencies
markdown:	kramdown
highlighter:	pygments

# Permalinks
permalink:	/:categories/:year/:month/:day/:title

# Setup
title:		Agus Lopez
tagline:	'blog'
description:	'My personal blog.'
url:		http://aguslr.github.io
commentsystem:	disqus
disqus:		aguslr

author:
  name:		'Agus Lopez'
  url:		https://twitter.com/aguslr

paginate:	5

# Custom vars
icon:		/assets/images/icon.png
cover:		/assets/images/cover.png

social:
  - icon:	twitter
    url:	https://twitter.com/aguslr
    desc:	Twitter

  - icon:	github
    url:	https://github.com/aguslr/
    desc:	GitHub

  - icon:	feed
    url:	/atom.xml
    desc:	RSS

menu:
  - title:	Home
    url:	/

  - title:	Archive
    url:	/archive/

  - title:	About
    url:	/about.html

copyright:
  author:	Agus Lopez
  url:		http://aguslr.github.io
  type_title:	Some rights reserved
  type_url:	http://creativecommons.org/licenses/by-nc/4.0/

# Google Analytics
google_analytics: 'UA-30522223-1'
